site_name: UpCluster
theme:
  name: active-handout-theme
  # locale: pt_BR

docs_dir: content
site_dir: docs

site_url: https://insper.github.io/UpCluster/
repo_name: "UpCluster"
repo_url: https://github.com/insper/UpCluster/
edit_uri: edit/main/content/


plugins:
  - active-handout

markdown_extensions:
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: content
      check_paths: true
  - md_in_html

extra_css:
    - equipe.css
    - stylesheet.css
    
nav:
    - "Building a cluster":
      - building-cluster/infrastructure/index.md
      - "Hardware  Infrastructure":
        - building-cluster/infrastructure/Hardware-Infrastructure/index.md
        - building-cluster/infrastructure/Hardware-Infrastructure/BIOS.md
      - "Physical Infrastructure": 
        - building-cluster/infrastructure/Physical-Infrastructure/index.md
      - "Operational System":
        - building-cluster/infrastructure/Operational-System/index.md
        - building-cluster/infrastructure/Operational-System/UpBoard-Setup/index.md
    - Aplications:
      - Aplications/index.md

